name: build linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.5"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      
    - name: build linux
      run: make
