name: norminette

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.5"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      
    - name: norminette
      run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette && norminette ./sources/